CREATE TABLE IF NOT EXISTS documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    document_number varchar(50) NOT NULL,
    department varchar(100) NOT NULL,
    owner_name varchar(120) NOT NULL,
    status varchar(20) NOT NULL,
    description varchar(1000) NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    deleted_at_utc timestamp with time zone NULL,
    CONSTRAINT uq_documents_document_number UNIQUE (document_number),
    CONSTRAINT ck_documents_status CHECK (status IN ('Draft', 'Review', 'Approved', 'Archived'))
);

CREATE INDEX IF NOT EXISTS ix_documents_not_deleted_updated
    ON documents (updated_at_utc DESC)
    WHERE deleted_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS ix_documents_search_title
    ON documents (lower(title));

CREATE INDEX IF NOT EXISTS ix_documents_search_document_number
    ON documents (lower(document_number));
