CREATE TABLE IF NOT EXISTS documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    document_number varchar(50) NOT NULL,
    department varchar(100) NOT NULL,
    owner_name varchar(120) NOT NULL,
    status varchar(20) NOT NULL,
    description varchar(1000) NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    deleted_at_utc timestamp with time zone NULL,
    CONSTRAINT uq_documents_document_number UNIQUE (document_number),
    CONSTRAINT ck_documents_status CHECK (status IN ('Draft', 'Review', 'Approved', 'Archived'))
);

CREATE INDEX IF NOT EXISTS ix_documents_not_deleted_updated
    ON documents (updated_at_utc DESC)
    WHERE deleted_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS ix_documents_search_title
    ON documents (lower(title));

CREATE INDEX IF NOT EXISTS ix_documents_search_document_number
    ON documents (lower(document_number));

CREATE TABLE IF NOT EXISTS invoices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number varchar(50) NOT NULL,
    customer_name varchar(150) NOT NULL,
    invoice_date date NOT NULL,
    due_date date NOT NULL,
    status varchar(30) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    tax_amount numeric(12, 2) NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    notes varchar(1000) NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NULL,
    deleted_at_utc timestamp with time zone NULL,
    CONSTRAINT uq_invoices_invoice_number UNIQUE (invoice_number),
    CONSTRAINT ck_invoices_due_date CHECK (due_date >= invoice_date),
    CONSTRAINT ck_invoices_amounts CHECK (
        subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_invoices_not_deleted_updated
    ON invoices (updated_at_utc DESC)
    WHERE deleted_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS ix_invoices_search_invoice_number
    ON invoices (lower(invoice_number));

CREATE INDEX IF NOT EXISTS ix_invoices_search_customer_name
    ON invoices (lower(customer_name));
